name: Linux
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install.
        run: source install.sh
      - name: Export.
        run: source export.sh